# Generated by Django 3.1.4 on 2020-12-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_news3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=300)),
                ('news_detail', models.TextField()),
                ('news_center', models.CharField(max_length=300)),
                ('news_photo', models.ImageField(default='', upload_to='Photo')),
                ('news_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tb_news2',
        ),
    ]
